#!/bin/bash
# Meltdown Navigator - Deployment Commands
# Run these commands in your terminal

echo "🚀 Meltdown Navigator Deployment"
echo ""
echo "Step 1: Install nvm (if needed)"
echo "  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash"
echo "  source ~/.zshrc"
echo ""
echo "Step 2: Install Node.js 20"
echo "  nvm install 20"
echo "  nvm use 20"
echo "  nvm alias default 20"
echo ""
echo "Step 3: Install dependencies"
echo "  cd /Users/ogowemr/meltdown-navigator"
echo "  npm install --workspaces --include-workspace-root"
echo ""
echo "Step 4: Build"
echo "  cd backend && npm run build && cd .."
echo "  cd frontend && npm run build && cd .."
echo ""
echo "Step 5: Start services (in separate terminals)"
echo "  Terminal 1: cd backend && npm run start:prod"
echo "  Terminal 2: cd frontend && npm run start"
echo ""
echo "✅ Your API key is already set!"
echo "📍 Access: http://localhost:3000"
